'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

test('games overlay is mapped and uses DOM-safe rendering hooks', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'pages', 'overlays', 'games.html'), 'utf8');
  const script = fs.readFileSync(path.join(__dirname, '..', 'public', 'js', 'overlays', 'games.js'), 'utf8');
  const styles = fs.readFileSync(path.join(__dirname, '..', 'public', 'css', 'overlays', 'games.css'), 'utf8');
  assert.match(html, /id="gameStage"/);
  assert.match(script, /textContent/);
  assert.doesNotMatch(script, /innerHTML/);

  assert.match(html, /直播小游戏/);
  assert.doesNotMatch(html, /THE HIDDEN SPARK|BLACK × WHITE|LIVE ARCADE/);
  assert.doesNotMatch(html, /bomb-range-visual|game-atmosphere/);
  assert.doesNotMatch(script, /URLSearchParams|params\.get\(['"]game/);
  assert.match(script, /(?:nextSession|session)\?\.game/);
  assert.match(html, /id="gomokuColumnLabels"/);
  assert.match(html, /id="gomokuRowLabels"/);
  assert.match(html, /id="gameResultAvatar"/);
  assert.match(html, /id="drawGuessView"/);
  assert.match(html, /id="drawCanvas"/);
  assert.match(html, /id="drawScoreboard"/);
  assert.match(html, /id="drawCorrectFeed"/);
  assert.match(html, /id="drawClearBtn"/);
  assert.match(html, /id="drawPenBtn"[^>]+aria-label="画笔"/);
  assert.match(html, /id="drawEraserBtn"[^>]+aria-label="橡皮擦"/);
  assert.doesNotMatch(html, />橡皮擦</);
  assert.doesNotMatch(html, /drawDanmakuCount|\d+ 条/);
  assert.doesNotMatch(html, /gomoku-legend|gomokuHint|gomokuLastMove/);
  assert.match(script, /renderGomokuCoordinates\(state\.size\)/);
  assert.match(script, /cache:\s*['"]no-store['"]/);
  assert.match(script, /Authorization:\s*`Bearer \$\{token\}`/);
  assert.match(script, /INITIAL_SNAPSHOT_RETRIES/);
  assert.match(script, /scheduleSnapshotRetry/);
  assert.match(script, /api\/games\/winner-profile/);
  assert.match(script, /loadWinnerProfile[\s\S]+Authorization:\s*`Bearer \$\{token\}`/);
  assert.match(script, /function avatarSource\(/);
  assert.match(script, /api\/bilibili\/avatar\?url=/);
  assert.match(script, /image\.src\s*=\s*avatarSource\(item\.avatarUrl\)/);
  assert.match(script, /avatar\.src\s*=\s*avatarSource\(profile\.avatarUrl\)/);
  assert.match(script, /getBoundingClientRect/);
  assert.match(script, /positionGameResult/);
  assert.match(script, /game:draw/);
  assert.match(script, /pointerdown/);
  assert.match(script, /pointermove/);
  assert.match(script, /pointerup/);
  assert.match(script, /api\/games\/session\/draw/);
  assert.match(script, /getContext\(['"]2d['"]\)/);
  assert.match(script, /renderDrawGuess/);
  assert.match(script, /Object\.prototype\.hasOwnProperty\.call\(payload\.state, ['"]games['"]\)/);
  assert.doesNotMatch(script, /payload\.state\?\.games \|\| null/);
  assert.match(script, /revealedAnswer/);
  assert.match(script, /drawClientId/);
  assert.match(styles, /\.game-result\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(styles, /\.game-result\s*\{\s*position:\s*absolute/);
  assert.match(styles, /--gomoku-size:\s*min\(56vh, 520px/);
  assert.match(styles, /\.gomoku-cell::before/);
  assert.match(styles, /\.gomoku-cell:nth-child\(15n \+ 1\)/);
  assert.match(styles, /\.draw-canvas/);
  assert.match(styles, /\.draw-scoreboard/);
  assert.match(styles, /\.draw-tool-button\[aria-pressed=['"]true['"]\]/);
});
