'use strict';

const SHOTS = [
  { id: 'E1', file: 'toolbox-nav', title: '百宝箱导航：直播互动、直播画面与主播工作', main: 'otherAssistantPage' },
  {
    id: 'E1b',
    file: 'toolbox-nav-help',
    title: '百宝箱导航：软件与帮助',
    feature: 'otherUsageGuideFeature',
    mustShow: ['[data-other-feature="otherSettingsFeature"]', '[data-other-feature="otherDesktopUpdateFeature"]'],
  },
  {
    id: 'E2',
    file: 'danmaku-connection',
    title: '弹幕姬连接状态（未登录、未设置直播间）',
    feature: 'otherDanmakuFeature',
  },
  {
    id: 'E3',
    file: 'danmaku-styles',
    title: '六种固定样式与三种全屏随机样式',
    feature: 'otherDanmakuFeature',
    clip: '.danmaku-style-picker',
  },
  {
    id: 'E4',
    file: 'danmaku-send',
    title: '弹幕输入、发送与自动钓鱼入口',
    feature: 'otherDanmakuFeature',
    clip: '.danmaku-compose-section',
  },
  {
    id: 'E5',
    file: 'danmaku-blacklist',
    title: '用户黑名单与敏感词屏蔽（示例数据）',
    feature: 'otherDanmakuFeature',
    clip: '#danmakuOverlayFilters',
  },
  {
    id: 'E6',
    file: 'danmaku-params',
    title: '深色面板字体、颜色与透明度',
    feature: 'otherDanmakuFeature',
    clip: '.danmaku-parameters',
  },
  {
    id: 'E6b',
    file: 'danmaku-random-params',
    title: '全屏随机样式停留时间与应用按钮',
    feature: 'otherDanmakuFeature',
    click: '[data-danmaku-style="outline"]',
    scroll: '.danmaku-parameters',
    mustShow: ['#danmakuFullscreenDurationSeconds', '#danmakuApplyOverlayBtn'],
  },
  {
    id: 'E6c',
    file: 'danmaku-apply-style',
    title: '深色面板参数与应用到直播画面',
    feature: 'otherDanmakuFeature',
    scroll: '.danmaku-parameters',
    mustShow: ['#danmakuApplyOverlayBtn'],
  },
  {
    id: 'E7',
    file: 'ai-assistant-config',
    title: 'AI 互动助手配置（未填写密钥）',
    feature: 'otherDanmakuFeature',
    clip: '#xiaomiAiSection',
  },
  {
    id: 'E7b',
    file: 'ai-assistant-provider-menu',
    title: 'AI 平台选择（展开下拉框）',
    feature: 'otherDanmakuFeature',
    scroll: '#xiaomiAiTitle',
    click: '#xiaomiAiModelProvider-trigger',
    mustShow: ['#xiaomiAiModelProvider-trigger'],
  },
  { id: 'E8', file: 'dynamic-lottery-setup', title: '动态抽奖设置（未登录）', feature: 'otherDynamicLotteryFeature' },
  { id: 'E10', file: 'toolbox-games', title: '小游戏入口与启动设置', feature: 'otherGamesFeature' },
  {
    id: 'E10d',
    file: 'toolbox-draw-guess',
    title: '你画我猜回合与题库设置',
    feature: 'otherGamesFeature',
    click: '#drawCardTrigger',
    scroll: '[data-game-card="draw-guess"]',
    mustShow: ['#drawTotalRounds', '#drawRoundDuration'],
  },
  {
    id: 'E10f',
    file: 'toolbox-draw-board',
    title: '你画我猜主持区、快捷键与开始入口（未开局）',
    feature: 'otherGamesFeature',
    click: '#drawCardTrigger',
    scroll: '#drawHostTitle',
    mustShow: ['[data-start-game="draw-guess"]'],
  },
  {
    id: 'E10e',
    file: 'toolbox-wheel',
    title: '转盘内容、份数与独立网页入口',
    feature: 'otherGamesFeature',
    click: '#wheelCardTrigger',
    scroll: '#wheelCategoryTitle',
    mustShow: ['#wheelOverlayUrl', '#wheelSaveBtn', '#wheelSpinBtn'],
  },
  {
    id: 'E10b',
    file: 'toolbox-voting',
    title: '投票与评分设置',
    feature: 'otherGamesFeature',
    clip: '#interactionsAdmin',
  },
  {
    id: 'E11',
    file: 'toolbox-overtime-rule',
    title: '加班机礼物规则编辑',
    feature: 'otherOvertimeMachineFeature',
    clip: '#overtimeRules',
    setup: async (page) => {
      await page.locator('.overtime-rule-toggle').first().click();
    },
  },
  {
    id: 'E11b',
    file: 'toolbox-overtime-controls',
    title: '加班机初始时间、启用与开始暂停',
    feature: 'otherOvertimeMachineFeature',
    mustShow: ['#overtimeApplyTimeBtn', '#overtimeStartBtn', '#overtimePauseBtn'],
  },
  {
    id: 'E11c',
    file: 'toolbox-overtime-settlements',
    title: '加班机最近结算与直播画面入口（暂无结算）',
    feature: 'otherOvertimeMachineFeature',
    wait: '#overtimeSettlements .overtime-settlement-empty',
    scroll: '#overtimeSettlements',
    mustShow: ['#overtimeSettlements'],
  },
  { id: 'E12', file: 'toolbox-gift-effects', title: '礼物特效 ID、测试与画面链接', feature: 'otherGiftEffectsFeature' },
  { id: 'E13', file: 'toolbox-planner', title: '主播工作台日历、备忘与待办', feature: 'otherDailyTodoFeature' },
  {
    id: 'E14',
    file: 'toolbox-desktop-update',
    title: '检查更新、自动更新与目录入口（演示状态）',
    feature: 'otherDesktopUpdateFeature',
  },
  {
    id: 'E14b',
    file: 'toolbox-update-download',
    title: '发现新版本与下载按钮（演示状态）',
    feature: 'otherDesktopUpdateFeature',
    update: { status: 'available', version: '5.0.4', canDownload: true, message: '发现新版本 5.0.4，可以下载更新。' },
  },
  {
    id: 'E14c',
    file: 'toolbox-update-ready',
    title: '重启并更新（演示状态）',
    feature: 'otherDesktopUpdateFeature',
    update: { status: 'downloaded', version: '5.0.4', canInstall: true, message: '更新已下载完成，重启后安装。' },
  },
  { id: 'E15', file: 'gift-frame-settings', title: '礼物边框金额、动效与预览', feature: 'otherGiftFeature' },
  {
    id: 'E16',
    file: 'gift-feed-settings',
    title: '滚动礼物分色、行数与滚动速率',
    feature: 'otherGiftFeature',
    click: '#giftAssistantDisplayTab',
  },
  { id: 'E17', file: 'toolbox-clock', title: '萌时钟六种风格与预览', feature: 'otherClockFeature' },
  { id: 'E18', file: 'toolbox-opening', title: '开播动画文案、画质与素材', feature: 'otherStartAnimationFeature' },
  {
    id: 'E18b',
    file: 'toolbox-opening-audio',
    title: '开播动画人物、音乐、音量与地址',
    feature: 'otherStartAnimationFeature',
    scroll: '#openingCharacterHeading',
    mustShow: ['#openingAudioVolume', '#openingCopyUrl'],
  },
  { id: 'E19', file: 'toolbox-fan-profiles', title: '粉丝档案入口与筛选', feature: 'otherFanProfilesFeature' },
  { id: 'E20', file: 'toolbox-settings', title: '账户与网站设置（示例账号）', feature: 'otherSettingsFeature' },
  { id: 'E21', file: 'toolbox-performance', title: '性能页与本机硬件入口', feature: 'otherPerformanceFeature' },
  {
    id: 'E10c',
    file: 'toolbox-rating',
    title: '观众评分范围与平均分显示设置',
    feature: 'otherGamesFeature',
    click: '#interactionRatingTab',
    clip: '#interactionsAdmin',
  },
  {
    id: 'E13b',
    file: 'toolbox-planner-event',
    title: '新建日程的日期、时间与分类',
    feature: 'otherDailyTodoFeature',
    setup: async (page) => {
      await page.locator('[data-event-new]').first().click();
      await page.locator('#plannerEventTitle').fill('示例歌回');
      await page.locator('#plannerEventTime').fill('20:00');
    },
    clip: '#plannerEventDialog',
  },
  {
    id: 'E19b',
    file: 'fan-profiles-settings',
    title: '粉丝档案设置：同步与备份',
    feature: 'otherFanProfilesFeature',
    click: '#fanSettingsTab',
  },
  {
    id: 'E19c',
    file: 'fan-profiles-create',
    title: '新建粉丝档案：基本信息上半部',
    feature: 'otherFanProfilesFeature',
    click: '#fanNewProfileButton',
    mustShow: ['#fanSaveButton'],
  },
  {
    id: 'E19i',
    file: 'fan-profiles-basic-tags',
    title: '新建粉丝档案：标签与特别关注',
    feature: 'otherFanProfilesFeature',
    click: '#fanNewProfileButton',
    setup: async (page) => {
      await page.locator('#fanEditorFields [name="tags"]').scrollIntoViewIfNeeded();
    },
    mustShow: ['#fanEditorFields [name="tags"]', '#fanEditorFields [name="favorite"]'],
  },
  {
    id: 'E19d',
    file: 'fan-profiles-management',
    title: '粉丝档案设置：档案管理',
    feature: 'otherFanProfilesFeature',
    click: '#fanSettingsTab',
    scroll: '#fanSettingsProfilesTitle',
    mustShow: ['[data-fan-action="suppressions"]', '[data-fan-action="archived"]', '[data-fan-action="delete-all"]'],
  },
  {
    id: 'E19e',
    file: 'fan-profiles-personal',
    title: '新建粉丝档案：生日与偏好',
    feature: 'otherFanProfilesFeature',
    click: ['#fanNewProfileButton', '#fanProfilePersonalTab'],
    size: [1440, 1100],
  },
  {
    id: 'E19f',
    file: 'fan-profiles-notes',
    title: '新建粉丝档案：记录与提醒',
    feature: 'otherFanProfilesFeature',
    click: ['#fanNewProfileButton', '#fanProfileNotesTab'],
    size: [1440, 1100],
  },
  {
    id: 'E19g',
    file: 'fan-profiles-detail',
    title: '选中粉丝后的档案详情',
    feature: 'otherFanProfilesFeature',
    click: '[data-fan-id]:first-child',
    mustShow: ['#fanDetail'],
  },
  {
    id: 'E19h',
    file: 'fan-profiles-reminders',
    title: '粉丝档案提醒页（暂无提醒）',
    feature: 'otherFanProfilesFeature',
    click: '#fanRemindersTab',
  },
  {
    id: 'E22',
    file: 'danmaku-reply-tools',
    title: '回复与辅助：签到、抽签、欢迎与 PK',
    feature: 'otherDanmakuFeature',
    scroll: '#danmakuFixedReplyTitle',
    size: [1440, 1040],
  },
  {
    id: 'E22b',
    file: 'danmaku-custom-reply',
    title: '自定义关键词与回复编辑',
    feature: 'otherDanmakuFeature',
    click: '[data-fixed-open="diy"]',
    scroll: '#danmakuCustomRepliesPanel',
  },
  {
    id: 'E22c',
    file: 'danmaku-welcome-settings',
    title: '进场欢迎参数与词库入口（演示草稿）',
    feature: 'otherDanmakuFeature',
    click: '[data-fixed-open="welcome"]',
    setup: async (page) => {
      await page.locator('#danmakuWelcomewelcomeDelaySeconds').fill('5');
      await page.locator('#danmakuWelcomewelcomeMinHonorLevel').fill('10');
    },
    scroll: '#danmakuFixedEditorHeading',
    size: [1440, 1040],
  },
  {
    id: 'E22d',
    file: 'danmaku-pk-settings',
    title: 'PK 对手信息播报说明',
    feature: 'otherDanmakuFeature',
    click: '[data-fixed-open="pk"]',
    scroll: '#danmakuFixedReplyTitle',
  },
  {
    id: 'F2a',
    file: 'client-song-page-link',
    title: '客户端查看网页歌单入口',
    tab: 'importPage',
    clip: '#licenseSongSync',
  },
  {
    id: 'F2b',
    file: 'client-song-sync-result',
    title: '覆盖同步确认后的反馈（接口演示）',
    tab: 'importPage',
    setup: async (page) => {
      await page.locator('#licenseSyncSongsBtn').click();
      await page.getByRole('button', { name: '覆盖同步', exact: true }).click();
      await page.locator('#licenseSyncResult').filter({ hasText: '已同步' }).waitFor();
    },
    scroll: '#licenseSongSync',
  },
  {
    id: 'F3a',
    file: 'client-song-page-background',
    title: '客户端当前背景与恢复默认背景（示例图片）',
    tab: 'importPage',
    background: true,
    scroll: '#licenseSongBackground',
    mustShow: ['#licenseSongBgDeleteBtn', '#licenseSongBgPickBtn'],
  },
];

module.exports = { SHOTS };
