'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { startCanvasOutputFixture, openCanvasDesktop } = require('../helpers/canvas-output-fixture');

test('empty editor adds independent styles and publishes every layer through one persistent source', { timeout: 45000 }, async t => {
  const fixture = await startCanvasOutputFixture();
  const browser = await chromium.launch({ headless: true });
  const desktop = await browser.newPage();
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const output = await browser.newPage({ viewport: { width: 1920, height: 1080 } });
  const errors = [];
  for (const target of [desktop, page, output]) target.on('pageerror', error => errors.push(error.message));
  t.after(async () => { await browser.close(); await fixture.close(); assert.deepEqual(errors, []); });
  await page.addInitScript(() => {
    Object.defineProperty(navigator, 'clipboard', { value: { writeText: async value => { window.copiedSource = value; } } });
  });
  const url = await openCanvasDesktop(desktop, fixture);
  assert.equal(new URL(url).searchParams.has('component'), false);
  assert.equal((await fetch(url)).status, 200);
  await page.goto(url);
  await page.getByRole('button', { name: '添加组件', exact: true }).waitFor();
  assert.equal(await page.locator('.scene-editor-item').count(), 0);
  assert.equal(await page.locator('.component-preview-add').count(), 1);
  assert.equal(await page.locator('.preview-canvas-resolution').textContent(), '1920 × 1080');
  const add = async (category, style) => {
    await page.getByRole('button', { name: '添加组件', exact: true }).click();
    await page.locator(`[data-category="${category}"]`).click();
    await page.locator(`[data-picker-style="${style}"]`).click();
  };
  await add('clock', 'peach');
  assert.equal(await page.getByRole('spinbutton', { name: 'X', exact: true }).inputValue(), '670');
  await add('clock', 'flip');
  await add('queue', 'classic');
  await add('danmaku', 'signal');
  await add('overtime', 'default');
  assert.equal(await page.locator('iframe').count(), 5);
  await page.locator('.preview-canvas-layer-select').filter({ hasText: '萌时钟 1' }).click();
  await page.locator('[data-preview-field="clockCustomLabel"]').fill('仅第一只时钟');
  await page.getByRole('button', { name: '保存并应用', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '已保存并应用到直播源' }).waitFor();
  const first = fixture.service.list()[0];
  assert.equal(first.publishedVersion, 1);
  assert.equal(first.document.items.length, 5);
  const clocks = first.document.items.filter(item => item.type === 'clock');
  assert.deepEqual(clocks.map(item => item.appearance.config.style), ['peach', 'flip']);
  assert.equal(clocks[0].appearance.config.label, '仅第一只时钟');
  assert.notEqual(clocks[1].appearance.config.label, '仅第一只时钟');
  assert.ok(first.document.items.every(item => item.appearance.mode === 'independent'));
  await page.getByRole('button', { name: '复制直播源地址', exact: true }).click();
  await page.waitForFunction(() => window.copiedSource);
  const source = await page.evaluate(() => window.copiedSource);
  const address = new URL(source);
  assert.equal(address.hostname, '127.0.0.1');
  assert.equal(address.pathname, '/scene');
  assert.equal(address.searchParams.get('id'), first.document.id);
  assert.equal((await fetch(source)).status, 200);
  await output.goto(source);
  await output.waitForFunction(() => document.querySelectorAll('.scene-version:not(.is-staging) iframe').length === 5);
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="点歌板 1"]').getByText('合成实时歌曲').waitFor();
  assert.equal(await output.frameLocator('.scene-version:not(.is-staging) iframe[title="萌时钟 2"]').locator('html').getAttribute('data-clock-style'), 'flip');
  const danmaku = output.frames().find(frame => new URL(frame.url()).pathname === '/danmaku');
  assert.equal(new URL(danmaku.url()).searchParams.get('componentLayer'), '1');
  assert.equal(await danmaku.getByText('示例观众', { exact: true }).count(), 0);
  for (const frame of output.frames().filter(frame => frame.parentFrame())) {
    assert.equal(await frame.evaluate(() => window.__API_TOKEN__), undefined);
    assert.equal(frame.url().includes(address.hash), false);
  }
  fixture.failPublication(true);
  await page.locator('[data-preview-field="clockCustomLabel"]').fill('更新后的时钟');
  await page.getByRole('button', { name: '保存并应用', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '模拟发布失败' }).waitFor();
  assert.equal(fixture.service.list()[0].publishedVersion, 1);
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="萌时钟 1"]').getByText('仅第一只时钟').waitFor();
  fixture.failPublication(false);
  await page.getByRole('button', { name: '保存并应用', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '已保存并应用到直播源' }).waitFor();
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="萌时钟 1"]').getByText('更新后的时钟').waitFor();
  await page.getByRole('button', { name: '复制直播源地址', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '直播源地址已复制' }).waitFor();
  assert.equal(await page.evaluate(() => window.copiedSource), source);
  await page.goto('about:blank');
  await desktop.evaluate(() => window.reopen());
  await desktop.waitForFunction(() => window.externalPreviewUrl);
  await page.goto(await desktop.evaluate(() => window.externalPreviewUrl));
  await page.waitForFunction(() => document.querySelectorAll('.scene-editor-item').length === 5);
  assert.equal(await page.getByRole('heading', { name: '公共画布设置', exact: true }).count(), 1);
  assert.equal(fixture.service.list().length, 1);
  await page.close();
  await desktop.close();
  await output.reload();
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="萌时钟 1"]').getByText('更新后的时钟').waitFor();
  fixture.runtime.queue.waiting[0].song_name = '关闭编辑器后的歌曲';
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="点歌板 1"]').getByText('关闭编辑器后的歌曲').waitFor();
  fixture.updateCloud({ type: 'danmaku', liveSessionId: 'synthetic-live', name: '合成观众', message: '关闭编辑器后的弹幕' });
  await output.frameLocator('.scene-version:not(.is-staging) iframe[title="弹幕姬 1"]').getByText('关闭编辑器后的弹幕').waitFor();
  assert.equal(await output.locator('body').evaluate(node => getComputedStyle(node).backgroundColor), 'rgba(0, 0, 0, 0)');
  assert.equal(await output.locator('.component-preview-body').count(), 0);
  await output.setViewportSize({ width: 1280, height: 720 });
  await output.waitForFunction(() => Math.round(document.querySelector('.scene-version:not(.is-staging)').getBoundingClientRect().width) === 1280);
  const size = await output.locator('.scene-version:not(.is-staging)').boundingBox();
  assert.equal(Math.round(size.height), 720);
});
